- project:
    templates:
      - check-requirements
      - openstack-python3-xena-jobs
      - publish-openstack-docs-pti
    check:
      jobs:
        - ec2api-tempest-plugin-functional
    gate:
      queue: ec2-api
      jobs:
        - ec2api-tempest-plugin-functional
    experimental:
      jobs:
        # TripleO jobs that deploy ec2-api.
        # Note we don't use a project-template here, so it's easier
        # to disable voting on one specific job if things go wrong.
        # If you need any support to debug these jobs in case of
        # failures, please reach us on #tripleo IRC channel.
        - tripleo-ci-centos-8-scenario002-standalone
