- project:
    queue: ec2-api
    templates:
      - check-requirements
      - openstack-python3-jobs
      - publish-openstack-docs-pti
    check:
      jobs:
        - ec2api-tempest-plugin-functional
    gate:
      jobs:
        - ec2api-tempest-plugin-functional
