- project:
    templates:
      - check-requirements
      - openstack-lower-constraints-jobs
      - openstack-python3-wallaby-jobs
      - publish-openstack-docs-pti
    check:
      jobs:
        - ec2api-tempest-plugin-functional
    gate:
      queue: ec2-api
      jobs:
        - ec2api-tempest-plugin-functional
    experimental:
      jobs:
        # TripleO jobs that deploy ec2-api.
        # Note we don't use a project-template here, so it's easier
        # to disable voting on one specific job if things go wrong.
        # tripleo-ci-centos-7-scenario002-multinode-oooq-container will
        # run in Pike and beyond.
        # If you need any support to debug these jobs in case of
        # failures, please reach us on #tripleo IRC channel.
        - tripleo-ci-centos-7-scenario002-standalone
