- project:
    templates:
      - check-requirements
      - openstack-lower-constraints-jobs
      - openstack-python3-yoga-jobs
      - publish-openstack-docs-pti
    check:
      jobs:
        - ec2api-tempest-plugin-functional
    gate:
      queue: ec2-api
      jobs:
        - ec2api-tempest-plugin-functional
